### PR TITLE
Feature/update viewer and fix build

### LINKED ISSUE #10: update to use new website-3d-volume-viewer
## Use Case

When UI overhaul is done and tested, we need to get nbvv to pick up the many updates (and bug fixes)...

## Solution

bump versions of volume-viewer and website-3d-cell-viewer, publish, and then update nbvv.  Test!

### PR DESCRIPTION
**Pull request by frasercl**
Resolves #10

The new version of the 3d volume viewer, 2.3, contains significant UI updates. It also depends on styles which are currently in this repo but not being imported properly. Update viewer and fix style building.

### CODE REVIEW

File: js/src/index.ts [hunk 1]
```diff
@@ -3,9 +3,8 @@ import { ImageViewerApp } from "@aics/web-3d-viewer";
 import React from "react";
 import ReactDOM from "react-dom";
 
-import "antd/dist/antd.css";
-// TODO: this starts as .less and needs to be converted to .css in tsc step
-import "./style.css";
+// Imported after tsc transpile - links out of lib, back into src
+import "../src/style.less";
```
Comment (toloudis) [inline js/src/index.ts:7]: TBH I think this looks a bit clunky - the path should be one that makes sense within this file. 
My preference would be to have a build step that simply copies the .less file into the `lib/` dir.  For example, reinstate the `build:css` step but just have it copy the file over.
And in the comment here, I'd say that we are using webpack's less-loader so we don't need to transpile this until webpack runs.

File: js/src/styles/ant-vars.less [hunk 2]
```diff
@@ -1,162 +1,162 @@
...
-@normal-color : @light-gray;
-@background-color : @dark-gray;
-@disabled-color : fade(@light-gray, 10%);
-@disabled-bg : @background-color;
+@primary-color: tint(@purple, 90%);
+@success-color: @bright-green;
+@highlight-color: @purple;
+@warning-color: @gold-6;
+@normal-color: @light-gray;
+@background-color: @dark-gray;
```
Comment (toloudis) [inline js/src/styles/ant-vars.less:12]: Are all the lines in this file actually needed?  Is it much different than the built-in styling? Just wondering if we could even remove most of this file.

File: js/webpack.prebuilt.config.js [hunk 3]
```diff
@@ -0,0 +1,29 @@
+// Custom webpack rules are generally the same for all webpack bundles, hence
+// stored in a separate local variable.
+const rules = [
```
Comment (toloudis) [inline js/webpack.prebuilt.config.js:3]: I'd suggest this file needs a comment on why it's even here.
```
// "jupyter labextension build" will run webpack on its own and use the contents of this file as additional rules.  
// We use less-loader here to get our css injected in properly.
```

File: js/src/styles/ant-vars.less (hunk 2 above)
Comment (frasercl) [reply js/src/styles/ant-vars.less:12]: Seems likely that we could trim a lot of it down, though in that case we'd be looking at resolving this across multiple repositories. (The diffs here are just from copying the version of this file in web-3d-viewer over this one.)

Really web-3d-viewer ought to be responsible for these variables, it makes no sense that users of this component would have to jump through these hoops. The fact that they do have to is in part down to how the viewer kind of fights ant's styling rather than playing nice with it (an issue which I've unfortunately perpetuated a bit). I've gone back and forth on how best to clean this up, and I'm currently thinking the best solution long-term is probably to move the viewer's styling to less so that it can use ant's variables, then provide a default theme file that looks like this and can be imported out of the viewer package.

File: js/src/index.ts (hunk 1 above)
Comment (frasercl) [reply js/src/index.ts:7]: Yeah I wasn't particularly satisfied with this solution either. Does it make sense to move `style.less` into the `styles` directory and copy that directory over into `lib/`? Otherwise we create the same problem one level down, where imports in `style.less` have to reach back out of `lib/` and into `src/`. Unfortunately no solution will be 100% nice without all the building happening in a single step, which I couldn't quite get working.

File: js/src/styles/ant-vars.less (hunk 2 above)
Comment (toloudis) [reply js/src/styles/ant-vars.less:12]: makes sense.  sounds like this file is good to go until we do the bigger change.

File: js/src/index.ts (hunk 1 above)
Comment (toloudis) [reply js/src/index.ts:7]: if the import is `import "./style.less"` then it will work in the context of reading this source code, and also in teh context of running webpack on the contents of the lib/ directory.  But that then requires that something copies the file into lib/ (aka package.json scripts).
I just feel that it's cleaner if it says `import "./style.less"` .  If you want to put it in a `styles` subdirectory that would be totally fine too.

**Review by toloudis — APPROVED** [review]
Thank you!  Looks good.
